// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj40eWCc0e9iPc9LyNadHFmPY9CofN1HY',
    appId: '1:277757048201:web:bad51b749cb00273c55d58',
    messagingSenderId: '277757048201',
    projectId: 'url-short-project-trial',
    authDomain: 'url-short-project-trial.firebaseapp.com',
    storageBucket: 'url-short-project-trial.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAVHpJ9p2TdBju9KYum-B-8eeFlxT0Abg',
    appId: '1:277757048201:android:367b2b9e196ef27dc55d58',
    messagingSenderId: '277757048201',
    projectId: 'url-short-project-trial',
    storageBucket: 'url-short-project-trial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaA4ri8n4v6O3HjYMiCLJytrgHIVlsmG4',
    appId: '1:277757048201:ios:fd484199f31727d7c55d58',
    messagingSenderId: '277757048201',
    projectId: 'url-short-project-trial',
    storageBucket: 'url-short-project-trial.firebasestorage.app',
    iosBundleId: 'com.example.urlShortenerProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaA4ri8n4v6O3HjYMiCLJytrgHIVlsmG4',
    appId: '1:277757048201:ios:fd484199f31727d7c55d58',
    messagingSenderId: '277757048201',
    projectId: 'url-short-project-trial',
    storageBucket: 'url-short-project-trial.firebasestorage.app',
    iosBundleId: 'com.example.urlShortenerProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj40eWCc0e9iPc9LyNadHFmPY9CofN1HY',
    appId: '1:277757048201:web:b7455fbd2c46336ac55d58',
    messagingSenderId: '277757048201',
    projectId: 'url-short-project-trial',
    authDomain: 'url-short-project-trial.firebaseapp.com',
    storageBucket: 'url-short-project-trial.firebasestorage.app',
  );
}
